### ISSUE TITLE
UI: Update error message when insufficient permissions for workspace

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/AzureTRE#2062]
I got "Error retrieving workspace" when clicking on a workspace within the web UI.

**Steps to reproduce**

1. Deploy TRE (commit `735ae301df542059015a360ffa0c18b0236ffec2`)
1. Deploy base workspace
1. Navigate to UI and click on the deployed workspace

Looking in the console logs, I see

```
useAuthApiCall.ts:44 
        
       No account object found, please refresh.
(anonymous) @ useAuthApiCall.ts:44
NotificationPanel.tsx:47 
        
       LOADING ALL OPERATIONS...
(anonymous) @ NotificationPanel.tsx:47
/api//workspaces/14a5ac49-c1bb-49b3-9d54-21bdad12b7f4/workspace-services:1 
     
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 403 (Forbidden)
useAuthApiCall.ts:104 
        
       Error calling /workspaces/14a5ac49-c1bb-49b3-9d54-21bdad12b7f4/workspace-services: 403 - Forbidden
(anonymous) @ useAuthApiCall.ts:104
NotificationPanel.tsx:56 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'workspaceServices')
    at NotificationPanel.tsx:56:130
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at l (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:25:9)
App.tsx:110 
        
       Workspace set Object
setWorkspace @ App.tsx:110
App.tsx:108 
        
       Workspace roles undefined
setRoles @ App.tsx:108
/api/workspaces/14a5ac49-c1bb-49b3-9d54-21bdad12b7f4/workspace-services:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 403 (Forbidden)
useAuthApiCall.ts:104 
        
       Error calling workspaces/14a5ac49-c1bb-49b3-9d54-21bdad12b7f4/workspace-services: 403 - Forbidden
(anonymous) @ useAuthApiCall.ts:104
VM2996 react_devtools_backend.js:4026 
        
       Workspace roles Array(0)
overrideMethod @ VM2996 react_devtools_backend.js:4026
VM2996 react_devtools_backend.js:4026 
        
       Workspace set Object
overrideMethod @ VM2996 react_devtools_backend.js:4026
VM2996 react_devtools_backend.js:4026 
        
       Workspace set Object
overrideMethod @ VM2996 react_devtools_backend.js:4026
VM2996 react_devtools_backend.js:4026 
        
       Workspace roles undefined
overrideMethod @ VM2996 react_devtools_backend.js:4026
/api/workspaces/14a5ac49-c1bb-49b3-9d54-21bdad12b7f4/workspace-services:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 403 (Forbidden)
VM2996 react_devtools_backend.js:4026```

**Comment by stuartleeks** [comment]
@jjgriff93 I tried signing out and back in as suggested, but still get the issue

**Comment by stuartleeks** [comment]
@damoodamoo - here you go:

```json
{
    "id": "14a5ac49-c1bb-49b3-9d54-21bdad12b7f4",
    "templateName": "tre-workspace-base",
    "templateVersion": "0.3.9",
    "properties": {
        "display_name": "manual-from-swagger",
        "description": "base workspace 2",
        "client_id": "<redacted>",
        "client_secret": "<redacted>",
        "address_space_size": "small",
        "address_space": "10.1.8.0/24",
        "register_aad_application": false,
        "workspace_owner_object_id": "<redacted>",
        "sp_id": "<redacted>",
        "scope_id": "api://<redacted>",
        "app_role_id_workspace_researcher": "<redacted>",
        "app_role_id_workspace_owner": "<redacted>",
        "tre_id": "tresl9",
        "azure_location": "southcentralus",
        "workspace_id": "b7f4"
    },
    "isActive": true,
    "isEnabled": true,
    "resourceType": "workspace",
    "deploymentStatus": "deployed",
    "etag": "\"bf043d9f-0000-0500-0000-62b021560000\"",
    "resourcePath": "/workspaces/14a5ac49-c1bb-49b3-9d54-21bdad12b7f4",
    "resourceVersion": 0,
    "user": {
        "id": "bdd3aa73-c911-4db0-a1ba-09808125fe86",
        "name": "stuartle@microsoft.com Leeks (HE/HIM)",
        "email": "",
        "roles": [
            "TREAdmin"
        ],
        "roleAssignments": []
    },
    "updatedWhen": 1655710036.506063,
    "history": [],
    "workspaceURL": "",
    "_rid": "CwM-AP0L6fIFAAAAAAAAAA==",
    "_self": "dbs/CwM-AA==/colls/CwM-AP0L6fI=/docs/CwM-AP0L6fIFAAAAAAAAAA==/",
    "_etag": "\"bf044ea2-0000-0500-0000-62b022e00000\"",
    "_attachments": "attachments/",
    "_ts": 1655710432
}
```

**Comment by marrobi** [comment]
Could it be an issue with the app reg details in the env file? think I've seen something similar before.

**Comment by damoodamoo** [comment]
Did the workspace you deployed create the AAD app with it, or did you have an existing one / use the auth script to create that workspace app?

**Comment by ross-p-smith** [comment]
Your user needs to be WorkspaceOwner or WorkspaceUser of the Workspace that you are using
