### ISSUE TITLE
Apache Guacamole connection to VMs fail "some time" after initial deployment.

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2224]
Over the recent days members of the team have experienced issues connecting to VMs using Apache Guacamole. It seems they work immediately after deployment, but at some point later they fail.

I have been using a workspace with auto create app registration.

> 169.254.129.1 - d25709a4-32e5-4896-842b-a8e5aee3f824 - mxxx.com [2022/07/06 12:18:04] guacamole-mrtredemo1-ws-034e-svc-8c3a.azurewebsites.net GET / "/guacamole/api/session/tunnels/f379806b-b676-4cad-b4ed-359683ecc2d1/protocol?token=xxx HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37" 200 5157 0.007 2022-07-06T12:18:04.337849513Z 12:18:04.337 [http-nio-8080-exec-9] DEBUG o.a.g.rest.RESTExceptionMapper - Client request rejected: No readable active connection for tunnel. 2022-07-06T12:18:04.345119445Z 169.254.129.1 - 7d7c9d94-e348-4e42-8266-5fbfe52f9e54 - marxxxcom [2022/07/06 12:18:04] guacamole-mrtredemo1-ws-034e-svc-8c3a.azurewebsites.net GET / "/guacamole/api/session/tunnels/f379806b-b676-4cad-b4ed-359683ecc2d1/activeConnection/connection/sharingProfiles" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37" 404 230 0.017 2022-07-06T12:18:08.136612060Z guacd[2178]: INFO: RDP server closed/refused connection: Connection failed (server unreachable?) 

Also seen errors such as:

> 022-07-07T07:49:39.327521976Z 07:49:39.327 [http-nio-8080-exec-10] DEBUG o.a.g.a.azuretre.user.TreUserContext - getAuthenticationProvider
2022-07-07T07:49:39.328328087Z 07:49:39.327 [http-nio-8080-exec-10] DEBUG o.a.g.a.azuretre.user.TreUserContext - getConnectionDirectory
2022-07-07T07:49:39.328887994Z 07:49:39.328 [http-nio-8080-exec-10] INFO o.a.g.a.a.c.TokenInjectingConnection - Loading credentials from Azure Key Vault for secret linuxvmcc57
2022-07-07T07:49:39.358138061Z 07:49:39.357 [http-nio-8080-exec-10] DEBUG c.a.identity.EnvironmentCredential - Azure Identity => Found the following environment variables: MSI_ENDPOINT, MSI_SECRET
2022-07-07T07:49:39.359227975Z 07:49:39.358 [http-nio-8080-exec-10] ERROR c.a.identity.EnvironmentCredential - Azure Identity => ERROR in EnvironmentCredential: Missing required environment variable AZURE_CLIENT_ID
2022-07-07T07:49:39.359948884Z 07:49:39.359 [http-nio-8080-exec-10] DEBUG c.a.i.ManagedIdentityCredential - Azure Identity => Found the following environment variables: MSI_ENDPOINT, MSI_SECRET
2022-07-07T07:49:39.360654093Z 07:49:39.360 [http-nio-8080-exec-10] DEBUG c.a.i.SharedTokenCacheCredential - Azure Identity => Found the following environment variables: MSI_ENDPOINT, MSI_SECRET
2022-07-07T07:49:39.362334514Z 07:49:39.360 [http-nio-8080-exec-10] ERROR c.a.i.i.IntelliJCacheAccessor - IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
2022-07-07T07:49:39.362353814Z com.azure.identity.CredentialUnavailableException: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
2022-07-07T07:49:39.362386615Z at com.azure.identity.implementation.IntelliJCacheAccessor.getAuthDetailsIfAvailable(IntelliJCacheAccessor.java:251)
2022-07-07T07:49:39.362392715Z at com.azure.identity.IntelliJCredential.<init>(IntelliJCredential.java:51)
2022-07-07T07:49:39.362397315Z at com.azure.identity.DefaultAzureCredentialBuilder.getCredentialsChain(DefaultAzureCredentialBuilder.java:132)
2022-07-07T07:49:39.362401715Z at com.azure.identity.DefaultAzureCredentialBuilder.build(DefaultAzureCredentialBuilder.java:123)
2022-07-07T07:49:39.362405915Z at org.apache.guacamole.auth.azuretre.connection.TokenInjectingConnection.getConnectionCredentialsFromProjectAPI(TokenInjectingConnection.java:74)
2022-07-07T07:49:39.362410215Z at org.apache.guacamole.auth.azuretre.connection.TokenInjectingConnection.connect(TokenInjectingConnection.java:49)
2022-07-07T07:49:39.362414515Z at org.apache.guacamole.tunnel.TunnelRequestService.createConnectedTunnel(TunnelRequestService.java:216)
2022-07-07T07:49:39.362418715Z at org.apache.guacamole.tunnel.TunnelRequestService.createTunnel(TunnelRequestService.java:347)
2022-07-07T07:49:39.362422915Z at org.apache.guacamole.tunnel.websocket.RestrictedGuacamoleWebSocketTunnelEndpoint.createTunnel(RestrictedGuacamoleWebSocketTunnelEndpoint.java:113)
2022-07-07T07:49:39.362427115Z at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.onOpen(GuacamoleWebSocketTunnelEndpoint.java:200)
2022-07-07T07:49:39.362431415Z at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:136)
2022-07-07T07:49:39.362435615Z at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:933)
2022-07-07T07:49:39.362439815Z at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
2022-07-07T07:49:39.362443916Z at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2022-07-07T07:49:39.362448216Z at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2022-07-07T07:49:39.362452316Z at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2022-07-07T07:49:39.362457216Z at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2022-07-07T07:49:39.362461616Z at java.base/java.lang.Thread.run(Unknown Source)
2022-07-07T07:49:39.362465916Z 07:49:39.362 [http-nio-8080-exec-10] INFO c.a.s.k.secrets.SecretAsyncClient - Retrieving secret - linuxvmcc57-admin-credentials
2022-07-07T07:49:39.369227201Z 07:49:39.369 [reactor-http-epoll-2] DEBUG r.n.r.PooledConnectionProvider - [id: 0x56b907d7, L:/169.254.254.3:56536 - R:kv-mrtredemo1-ws-034e.vault.azure.net/10.0.4.11:443] Channel acquired, now 1 active connections and 1 inactive connections

**Comment by martinpeck** [comment]
Is this related to the subscription bots downgrading stuff?
Is there anything we need to do to fix this, or can we simply close it?

**Comment by marrobi** [comment]
Closing as cannot be fixed in this project.

**Comment by Danny-Cooke-cCK** [comment]
@ross-p-smith i know this is closed, but we are experiencing this issue and i just wondered if you could expand on "This is down to the subscription having a tag placed on it" please ? whats the reason etc?

**Comment by ross-p-smith** [comment]
Hi Danny, from memory this was because we were using a subscription that had some automated processes that would use Azure Policies to add certain tags to subscriptions, it would also sometimes add networking policies that would interfere with the VM's. @marrobi would be the best one to talk to see what the latest is with this issue - it may be worth raising a new Issue and linking this one. Is it exactly the same stack trace you get?
