### ISSUE TITLE
Creating a user resource gives 409, then calling get user resources gives 500 error

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#2464]
Deploy new Workspace, Guacamole Workspace Service, try get User Resources.

Tried creating a user resource get:
```
2022-08-15T09:09:57.393090238Z INFO: 169.254.129.5:51812 - "POST /api/workspaces/b602ea8a-a0e2-4082-96a9-5279c11cf54c/workspace-services/c5837fa8-3d69-4585-b566-a30251e4d3d6/user-resources HTTP/1.1" 409 Conflict 
```

Then get:

```https://mytre.westeurope.cloudapp.azure.com/api/workspaces/05a22d7b-3dc5-47e7-aa07-05316bff5e65/workspace-services/23f8fbf7-376e-46e3-a754-fa2c1f035c73/user-resources```

Logs show:

```
022-08-15T09:09:05.563102014Z Traceback (most recent call last):
2022-08-15T09:09:05.563106714Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2022-08-15T09:09:05.563111514Z await self.app(scope, receive, _send)
2022-08-15T09:09:05.563116314Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 63, in __call__
2022-08-15T09:09:05.563121114Z response = await self.dispatch_func(request, call_next)
2022-08-15T09:09:05.563125714Z File "/api/./services/tracing.py", line 83, in dispatch
2022-08-15T09:09:05.563130514Z response = await call_next(request)
2022-08-15T09:09:05.563135214Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 44, in call_next
2022-08-15T09:09:05.563140014Z raise app_exc
2022-08-15T09:09:05.563144614Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
2022-08-15T09:09:05.563149314Z await self.app(scope, request.receive, send_stream.send)
2022-08-15T09:09:05.563154014Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
2022-08-15T09:09:05.563158814Z raise exc
2022-08-15T09:09:05.563163414Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
2022-08-15T09:09:05.563168114Z await self.app(scope, receive, sender)
2022-08-15T09:09:05.563172614Z File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2022-08-15T09:09:05.563177414Z raise e
2022-08-15T09:09:05.563182014Z File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2022-08-15T09:09:05.563186714Z await self.app(scope, receive, send)
2022-08-15T09:09:05.563192514Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
2022-08-15T09:09:05.563197514Z await route.handle(scope, receive, send)
2022-08-15T09:09:05.563202114Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
2022-08-15T09:09:05.563206914Z await self.app(scope, receive, send)
2022-08-15T09:09:05.563211514Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
2022-08-15T09:09:05.563219914Z response = await func(request)
2022-08-15T09:09:05.563224914Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
2022-08-15T09:09:05.563234114Z raw_response = await run_endpoint_function(
2022-08-15T09:09:05.563238914Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
2022-08-15T09:09:05.563243814Z return await dependant.call(**values)
2022-08-15T09:09:05.563248314Z File "/api/./api/routes/workspaces.py", line 278, in retrieve_user_resources_for_workspace_service
2022-08-15T09:09:05.563253114Z user_resource.azureStatus = get_azure_resource_status(user_resource.properties['azure_resource_id'])
2022-08-15T09:09:05.563257914Z File "/api/./services/azure_resource_status.py", line 15, in get_azure_resource_status
2022-08-15T09:09:05.563262714Z power_state = [x for x in vm_instance_view.statuses if x.code.startswith('PowerState')][0].display_status
2022-08-15T09:09:05.563267514Z TypeError: 'NoneType' object is not iterable
```

**Comment by marrobi** [comment]
The 500 error was caused by using old workspaces with newer verson of core - as per https://github.com/microsoft/AzureTRE/issues/2389 .

To work around I have added the `id-api-<TRE_ID>` to the workspace resource groups with `Virtual Machine Contributor` rights.
