### ISSUE TITLE
Nexus - curl: (7) Failed to connect - error

### ISSUE THREAD

**Issue by JaimieWi** [microsoft/AzureTRE#2877]
**Describe the bug**
When deploying a new TRE Nexus does not work. 

- Connecting to a VM and accessing Nexus via Edge displays a refused to connect page. 
- Connecting to the Nexus VM via the portal and running `curl https://nexus-trea44c387c.uksouth.cloudapp.azure.com` gives the below error.

```
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Tue Nov 15 09:02:20 2022 from 10.1.0.133
adminuser@nexus-trejaimie01:~$ curl https://nexus-trejaimie01.uksouth.cloudapp.azure.com
curl: (7) Failed to connect to nexus-trejaimie01.uksouth.cloudapp.azure.com port 443: Connection refused
```

_Nexus failing in all TREs, as seen by the variety of TRE_IDs_
**Steps to reproduce**

1. Deploy a new TRE based on the most recent commit (#2858).
2. Deploy a base Workspace and Virtual Machine.
3. Deploy Nexus as a Shared Service.
4. Access Nexus from within the VM. `refused to connect`
<img width="2049" alt="within_VM" src="https://user-images.githubusercontent.com/92854957/201883055-7aae7d25-19f8-4238-8b90-f942c9955fcd.png">
5. Access the admin Nexus VM via the portal and curl the URL. `Failed to connect.. connection refused`
<img width="1146" alt="within_Nexus_VM" src="https://user-images.githubusercontent.com/92854957/201883406-495b50b4-2f0c-45d0-9099-6b2cb6915172.png">

**Comment by RIashfaqahmed** [comment]
I am experiencing same issue for last 4 days Digging more in to Nexus VM, I discovered following errors in **/var/log/cloud-init-output.log**

```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/cloudinit/gpg.py", line 101, in recv_key
naplen = next(sleeps)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/gpg.py", line 130, in getkeybyid
    recv_key(keyid, keyserver=keyserver)
  File "/usr/lib/python3/dist-packages/cloudinit/gpg.py", line 112, in recv_key
    ) from e
ValueError: Failed to import key 'BC528686B50D79E339D3721CEB3E94ADBE1229CF' from keyserver 'hkp://keyserver.ubuntu.com:80' after 3 tries: Unexpected error while running command.
Command: ['gpg', '--no-tty', '--keyserver=hkp://keyserver.ubuntu.com:80', '--recv-keys', 'BC528686B50D79E339D3721CEB3E94ADBE1229CF']
Exit code: 2
Reason: -
Stdout:
Stderr: gpg: keyserver receive failed: No data
2022-11-15 17:46:48,420 - gpg.py[WARNING]: Failed delete key "BC528686B50D79E339D3721CEB3E94ADBE1229CF": Unexpected error while running command.
Command: ['gpg', '--batch', '--yes', '--delete-keys', 'BC528686B50D79E339D3721CEB3E94ADBE1229CF']
Exit code: 2
Reason: -
Stdout:
Stderr: gpg: key "BC528686B50D79E339D3721CEB3E94ADBE1229CF" not found: Not found
gpg: BC528686B50D79E339D3721CEB3E94ADBE1229CF: delete key failed: Not found
```


**Packages got failed to install**
```

2022-11-15 17:46:50,246 - util.py[WARNING]: Failed to install packages: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose', 'gnupg2', 'pass', 'azure-cli', 'default-jre', 'xmlst
arlet', 'jq']
2022-11-15 17:46:50,248 - cc_package_update_upgrade_install.py[WARNING]: 2 failed with exceptions, re-raising the last one
2022-11-15 17:46:50,249 - util.py[WARNING]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/c
loudinit/config/cc_package_update_upgrade_install.py'>) failed
/var/lib/cloud/instance/scripts/runcmd: 4: /var/lib/cloud/instance/scripts/runcmd: docker: not found
Checking for Nexus admin password file...
ERROR - Timeout while waiting for nexus-data/admin.password to be created
/etc/cron.daily/configure_nexus_ssl.sh: line 11: az: command not found
Checking for ./nexus_repos_config directory...
Found config file: /tmp/nexus_repos_config/almalinux_proxy_conf.json. Sending to Nexus...
/tmp/configure_nexus_repos.sh: line 27: jq: command not found
```

**Comment by marrobi** [comment]
I believe this is fixed in #2818 - I have deployed and not seen the issue from the latest release (which does not have this fix) but others have.

@jjgriff93 can you confirm you agree?

As a workaround use the templates in main until the PR is included in the release.

**Comment by jjgriff93** [comment]
Yes, this has been fixed and will be rolled out in the next release

**Comment by RIashfaqahmed** [comment]
Thanks @marrobi & @jjgriff93 , any expected timeframe for a new release having this fix? Since 0.6.0 is broken and I cannot proceed further without nexus. My other team members waiting to get TRE env up & running to carry on their Data related jobs.

Is there any other way I can get this working while new release is coming up?

**Comment by marrobi** [comment]
@RIashfaqahmed you can be unblicked immediately by taking the directory at `https://github.com/microsoft/AzureTRE/tree/main/templates/shared_services/sonatype-nexus-vm` and register it instead of the bundle in the release - as per https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/cicd-deplyment/#publish-custom-templates-in-pipelines

Expect the release be done in the next week or so.

If you are working with/for a specific Microsoft customer, please feel free to drop me an email on marcus.robinson at microsoft.com and can see how we can support you further.

**Comment by jjgriff93** [comment]
We're hoping to get a release through today, we're just waiting on a PR to go through. In the meantime, you can work around this issue by following the steps in my comment on the original bug: https://github.com/microsoft/AzureTRE/issues/2785. Let me know if you have any issues.

**Comment by marrobi** [comment]
@RIashfaqahmed @jjgriff93 - yes forgot about that workaround too. Might be a quicker short term fix.

**Comment by RIashfaqahmed** [comment]
@jjgriff93 I assume you are talking about https://github.com/microsoft/AzureTRE/issues/2785#issuecomment-1293314470 for  a quick interim solution?

**Comment by jjgriff93** [comment]
@RIashfaqahmed Yes that's the one, you'll need to SSH into the Nexus VM either using the serial console or Bastion (you can find the password in your TRE key vault, and the username will be 'adminuser')

**Comment by RIashfaqahmed** [comment]
@jjgriff93 you rock. Followed instructions and it worked like a charm. Thank you both @jjgriff93 & @marrobi

**Comment by jjgriff93** [comment]
No problem! Glad you're unblocked :)

**Comment by JaimieWi** [comment]
Hi @marrobi @jjgriff93. Sorry, that hasn't worked for me. 

For an existing TRE I ran the steps in #2785. I can then see the Nexus UI from within the VM but with no repositories listed. When looking at the /var/log/cloud-init-output.logs file I see the below error:

```
Nexus ssl configuration completed.
Checking for ./nexus_repos_config directory...
ERROR - Timeout while waiting for nexus_repos_config directory
2022-11-16 11:50:47,955 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2022-11-16 11:50:47,955 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.3.4-0ubuntu1~18.04.1 finished at Wed, 16 Nov 2022 11:50:48 +0000. Datasource DataSourceAzure [seed=/var/lib/waagent].  Up 516395.42 seconds
```

Also, I have deployed a brand new TRE based on the most recent commit in OSS #2873 and I see the same issue as stated in the original message. Looking at the `cloud-init-output.logs`, I see the error below:

```
E: Unable to locate package docker-compose
E: Package 'gnupg2' has no installation candidate
E: Unable to locate package pass
E: Unable to locate package xmlstarlet
E: Unable to locate package jq
Cloud-init v. 22.3.4-0ubuntu1~18.04.1 running 'modules:final' at Wed, 16 Nov 2022 11:13:50 +0000. Up 78.20 seconds.
2022-11-16 11:13:51,324 - util.py[WARNING]: Failed to install packages: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose', 'gnupg2', 'pass', 'azure-cli', 'default-jre', 'xmlstarlet', 'jq']
2022-11-16 11:13:51,387 - cc_package_update_upgrade_install.py[WARNING]: 1 failed with exceptions, re-raising the last one
2022-11-16 11:13:51,388 - util.py[WARNING]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_packa
ge_update_upgrade_install.py'>) failed
/var/lib/cloud/instance/scripts/runcmd: 4: /var/lib/cloud/instance/scripts/runcmd: docker: not found
Checking for Nexus admin password file...
ERROR - Timeout while waiting for nexus-data/admin.password to be created
/etc/cron.daily/configure_nexus_ssl.sh: line 11: az: command not found
Checking for ./nexus_repos_config directory...
Found config file: /tmp/nexus_repos_config/almalinux_proxy_conf.json. Sending to Nexus...
/tmp/configure_nexus_repos.sh: line 27: jq: command not found
/tmp/configure_nexus_repos.sh: line 28: jq: command not found
/tmp/configure_nexus_repos.sh: line 29: jq: command not found
Response received from Nexus: 000
Response received from Nexus: 000
Response received from Nexus: 000
....
ERROR - Timeout while trying to configure 
2022-11-16 11:23:56,756 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2022-11-16 11:23:56,756 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.3.4-0ubuntu1~18.04.1 finished at Wed, 16 Nov 2022 11:23:56 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 684.49 seconds
```

`cloud-init.logs`
```
2022-11-16 11:44:12,102 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2022-11-16 11:44:12,103 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/0974f91e-e18c-4744-a903-ac799e358c1b/sem/config_scripts_user - wb: [644] 25 bytes
2022-11-16 11:44:12,103 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/0974f91e-e18c-4744-a903-ac799e358c1b/sem/config_scripts_user'>)
2022-11-16 11:44:12,103 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/runcmd'] with allowed return codes [0] (shell=False, capture=False)
2022-11-16 11:50:47,955 - subp.py[DEBUG]: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/runcmd']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2022-11-16 11:50:47,955 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2022-11-16 11:50:47,955 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2022-11-16 11:50:47,955 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
2022-11-16 11:50:47,955 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 247, in _run_modules
    run_name, mod.handle, func_args, freq=freq
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 67, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 185, in run
    results = functor(*args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py", line 49, in handle
    subp.runparts(runparts_path)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 429, in runparts
    % (len(failed), ",".join(failed), len(attempted))
RuntimeError: Runparts: 1 failures (runcmd) in 1 attempted commands
```

**Comment by jjgriff93** [comment]
@JaimieWi Hmmm, could you check your firewall rules and see if there is an application rule group for nexus? Seems like it's a firewall issue as your Nexus VM is trying to get packages and failing. The change that you should have introduces a rule group that allows the package sources that Nexus needs within the core firewall deployment

**Comment by JaimieWi** [comment]
@jjgriff93 I may have found the issue, it seems when trying to curl the docker URL I see this error:
```
 curl https://download.docker.com/linux/ubuntu
<html>
<head><title>302 Moved Temporarily</title></head>
<body>
<h1>302 Moved Temporarily</h1>
<ul>
<li>Code: Found</li>
<li>Message: Resource Found</li>
<li>RequestId: 80BJACHKWRFT2MZH</li>
<li>HostId: 7aLrPOKeqnQg7QxZctxrmpm1dzkvNiyl211lfzXN+JMcYiLNsXQxfrbde8MBjdETaQ+aIHeeoAE=</li>
</ul>
<hr/>
</body>
</html>
```

Looking at the firewall logs I can't see that any of the `nexus-bootstrap` Target FQDN's are being denied.

**Comment by JaimieWi** [comment]
Hi @jjgriff93, We have found and solved the issue :D I am testing the full solution now but if it work would you like me to create a PR?

The issue came from none of the packages being outlined in the `sonatype-nexus-vm/cloud-config.yaml` being installed. Running `sudo apt install update` and then `sudo apt install <list_of_packages>` on the Nexus VM, allowed the runcmd script within /var/lib/cloud/instance/scripts/ to be run. 

Therefore, I am going to add `package_update: true` to the cloud-config.yaml, alongside the `package_upgrade: true` which is already there. I will test that in our pipeline now.

**Comment by jjgriff93** [comment]
Fantastic, yes please do PR it and I shall review. Thanks!

**Comment by JaimieWi** [comment]
Hi @marrobi @jjgriff93 I have created a PR with the changes that were required and explained the issue. Please let me know if there is anything that you'd like changed. I will close this issue now! Thanks!
