### ISSUE TITLE
Cost API returns 500 in a bare new deployed Azure TRE environment

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#2933]
**Describe the bug**
Cost API returns 500 in a bare new deployed Azure TRE environment.

![image](https://user-images.githubusercontent.com/3179107/206167745-5532e9a0-7929-4d6f-acd4-fcc1dd786561.png)

Error code from application insights:
```
Failed to query Azure TRE costs
Traceback (most recent call last):
File "/api/./api/routes/costs.py", line 63, in costs
return cost_service.query_tre_costs(
File "/api/./services/cost_service.py", line 147, in query_tre_costs
query_result = self.query_costs(CostService.TRE_ID_TAG, tre_id, granularity, from_date, to_date, list(resource_groups_dict.keys()))
File "/api/./services/cost_service.py", line 350, in query_costs
raise e
File "/api/./services/cost_service.py", line 320, in query_costs
return self.client.query.usage(self.scope, query_definition)
File "/usr/local/lib/python3.8/site-packages/azure/mgmt/costmanagement/operations/_query_operations.py", line 115, in usage
raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (BadRequest) Invalid query definition: Invalid dataset filter on Dimension column 'ResourceGroup'; comparison expression values is missing or empty.

(Request ID: 7258cc9c-bed5-4d6b-bd2d-9ebd5a95906a)
Code: BadRequest
Message: Invalid query definition: Invalid dataset filter on Dimension column 'ResourceGroup'; comparison expression values is missing or empty.

(Request ID: 7258cc9c-bed5-4d6b-bd2d-9ebd5a95906a)
```

**Steps to reproduce**

1. Deploy new Azure TRE environment.
1. Navigate to main page or query cost REST API using swagger UI.
1. Response from cost API should be with status code 500.
1. Search for error raised by Cost Management SDK in application insights,  should be like above.

**Comment by guybartal** [comment]
need to make sure first if its only a temporary behavior which goes away after few hours or consistent.

**Comment by guybartal** [comment]
closing #2949 as it just hides the permissions problem.
