### ISSUE TITLE
Container missing libraries

### ISSUE THREAD

**Issue by jgarcia-sg** [microsoft/AzureTRE#2970]
When running the docker file as in `AzureTRE/api-app`, I get the following issue:

```
microsoft/AzureTRE-Deployment#7 27.70       -- Configuring incomplete, errors occurred!
microsoft/AzureTRE-Deployment#7 27.70       See also "/tmp/pip-install-fgtjk0nc/uamqp_23006930b02c4360b81a4bf1f6ed20ed/build/temp.linux-aarch64-cpython-38/cmake/CMakeFiles/CMakeOutput.log".
microsoft/AzureTRE-Deployment#7 27.70       Traceback (most recent call last):
microsoft/AzureTRE-Deployment#7 27.70         File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
microsoft/AzureTRE-Deployment#7 27.70           main()
microsoft/AzureTRE-Deployment#7 27.70         File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
microsoft/AzureTRE-Deployment#7 27.70           json_out['return_val'] = hook(**hook_input['kwargs'])
microsoft/AzureTRE-Deployment#7 27.70         File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
microsoft/AzureTRE-Deployment#7 27.70           return _build_backend().build_wheel(wheel_directory, config_settings,
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 413, in build_wheel
microsoft/AzureTRE-Deployment#7 27.70           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
microsoft/AzureTRE-Deployment#7 27.70           self.run_setup()
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
microsoft/AzureTRE-Deployment#7 27.70           super(_BuildMetaLegacyBackend,
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
microsoft/AzureTRE-Deployment#7 27.70           exec(code, locals())
microsoft/AzureTRE-Deployment#7 27.70         File "<string>", line 260, in <module>
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
microsoft/AzureTRE-Deployment#7 27.70           return distutils.core.setup(**attrs)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
microsoft/AzureTRE-Deployment#7 27.70           return run_commands(dist)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
microsoft/AzureTRE-Deployment#7 27.70           dist.run_commands()
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
microsoft/AzureTRE-Deployment#7 27.70           self.run_command(cmd)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
microsoft/AzureTRE-Deployment#7 27.70           super().run_command(command)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
microsoft/AzureTRE-Deployment#7 27.70           cmd_obj.run()
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
microsoft/AzureTRE-Deployment#7 27.70           self.run_command("build")
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
microsoft/AzureTRE-Deployment#7 27.70           self.distribution.run_command(command)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
microsoft/AzureTRE-Deployment#7 27.70           super().run_command(command)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
microsoft/AzureTRE-Deployment#7 27.70           cmd_obj.run()
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
microsoft/AzureTRE-Deployment#7 27.70           self.run_command(cmd_name)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
microsoft/AzureTRE-Deployment#7 27.70           self.distribution.run_command(command)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
microsoft/AzureTRE-Deployment#7 27.70           super().run_command(command)
microsoft/AzureTRE-Deployment#7 27.70         File "/tmp/pip-build-env-03pwdyjd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
microsoft/AzureTRE-Deployment#7 27.70           cmd_obj.run()
microsoft/AzureTRE-Deployment#7 27.70         File "<string>", line 134, in run
microsoft/AzureTRE-Deployment#7 27.70         File "<string>", line 183, in build_cmake
microsoft/AzureTRE-Deployment#7 27.70         File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
microsoft/AzureTRE-Deployment#7 27.70           raise CalledProcessError(retcode, cmd)
microsoft/AzureTRE-Deployment#7 27.70       subprocess.CalledProcessError: Command 'cmake /tmp/pip-install-fgtjk0nc/uamqp_23006930b02c4360b81a4bf1f6ed20ed/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release' returned non-zero exit status 1.
microsoft/AzureTRE-Deployment#7 27.70       [end of output]
microsoft/AzureTRE-Deployment#7 27.70   
microsoft/AzureTRE-Deployment#7 27.70   note: This error originates from a subprocess, and is likely not a problem with pip.
microsoft/AzureTRE-Deployment#7 27.70   ERROR: Failed building wheel for uamqp
microsoft/AzureTRE-Deployment#7 27.70 Successfully built python-multipart
microsoft/AzureTRE-Deployment#7 27.70 Failed to build httptools psutil uamqp
microsoft/AzureTRE-Deployment#7 27.70 ERROR: Could not build wheels for psutil, uamqp, which is required to install pyproject.toml-based projects
microsoft/AzureTRE-Deployment#7 27.87 WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
microsoft/AzureTRE-Deployment#7 27.87 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

I could fix it by adding the following to the Dockerfile

```
FROM python:3.8-slim-buster as base
COPY requirements.txt /.
RUN apt-get update
RUN apt-get -y install build-essential cmake libsasl2-dev libldap2-dev libssl-dev
RUN pip3 install --no-cache-dir -r requirements.txt
```

Not sure how this could have worked before, so I might be doing something wrong or something might be wrong with my set up.

I ran this locally in my computer and not in the CI/CD.

Thank you

**Comment by marrobi** [comment]
Closing as no response and not seen elsewhere.
