### ISSUE TITLE
Airlock request fails to transition to in_review

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#3144]
**Describe the bug**
Sometimes, an airlock request will be _submitted_ but end up in a _failed_ status.

**Steps to reproduce**

Unknown, but the log is:

Failed processing Airlock request with ID: 'b7e0df6d-2fa1-4c31-a219-cc6100559ecd', changing request status to 'failed'.
Traceback (most recent call last):
File "/home/site/wwwroot/StatusChangedQueueTrigger/__init__.py", line 37, in main
handle_status_changed(request_properties, stepResultEvent, dataDeletionEvent, request_files)
File "/home/site/wwwroot/StatusChangedQueueTrigger/__init__.py", line 73, in handle_status_changed
blob_operations.create_container(containers_metadata.dest_account_name, req_id)
File "/home/site/wwwroot/shared_code/blob_operations.py", line 31, in create_container
blob_service_client.create_container(container_name)
File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
return func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_blob_service_client.py", line 531, in create_container
container.create_container(
File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
return func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 313, in create_container
return self._client.container.create( # type: ignore
File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
return func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 972, in create
pipeline_response = self._client._pipeline.run( # type: ignore # pylint: disable=protected-access
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
return first_node.send(pipeline_request) # type: ignore
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
[Previous line repeated 2 more times]
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 546, in send
raise err
File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 520, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 118, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/policies.py", line 313, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
response = self.next.send(request)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 103, in send
self._sender.send(request.http_request, **request.context.options),
File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 335, in send
return self._transport.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 382, in send
raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7fa20a1cb820>: Failed to establish a new connection: [Errno -2] Name or service not known

**Comment by marrobi** [comment]
Note to remind us that this is as a DNS record for the import storage account does not exist in the DNS zone. Despite the private endpoint showing that it does in the portal.

**Comment by eladiw** [comment]
Tried to reproduce on a fresh env. didn't happen.
@marrobi if it happens again, please ping me and I will take a look
