### ISSUE TITLE
State store migration fails on failed workspace 

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE#3214]
**Describe the bug**

`make db-migrate` can fail where cosmos contains resources that correspond to workspaces that have failed to deploy.  api logs:

```
2023-02-10T10:09:39.761582740Z INFO:root:PR 1717 - Shared services
2023-02-10T10:09:39.824579237Z INFO:root:PR 1726 - Authentication needs to be in properties so we can update them
2023-02-10T10:09:39.832641465Z ERROR:root:Failed to migrate database
2023-02-10T10:09:39.832683565Z Traceback (most recent call last):
2023-02-10T10:09:39.832688665Z File "/api/./api/routes/migrations.py", line 51, in migrate_database
2023-02-10T10:09:39.832692265Z migration_status = "Executed" if await workspace_migration.moveAuthInformationToProperties() else "Skipped"
2023-02-10T10:09:39.832695665Z File "/api/./db/migrations/workspaces.py", line 31, in moveAuthInformationToProperties
2023-02-10T10:09:39.832698965Z item["properties"]["scope_id"] = f"api://{item['properties']['client_id']}"
2023-02-10T10:09:39.832702365Z KeyError: 'client_id'
2023-02-10T10:09:39.835888016Z {'paths': ['/id'], 'kind': 'Hash', 'version': 2}
2023-02-10T10:09:39.835919516Z {'paths': ['/id'], 'kind': 'Hash', 'version': 2}
2023-02-10T10:09:39.835924616Z {'paths': ['/resourceId'], 'kind': 'Hash', 'version': 2}
2023-02-10T10:09:39.835927617Z {'paths': ['/id'], 'kind': 'Hash', 'version': 2}
2023-02-10T10:09:39.835930517Z {'paths': ['/id'], 'kind': 'Hash', 'version': 2}
2023-02-10T10:09:39.835933417Z {'paths': ['/id'], 'kind': 'Hash', 'version': 2}
2023-02-10T10:09:39.835936417Z {'paths': ['/id'], 'kind': 'Hash', 'version': 2}
2023-02-10T10:09:39.835939317Z INFO: x.x.x.x:x - "POST /api/migrations HTTP/1.1" 400 Bad Request
```

Deleting the workspaces without a `client_id` field from cosmos fixes the issue

**Steps to reproduce**

1. Deploy a workspace that does not succeed, due to an unrelated issue
1. Run `make db-migrate`

**Comment by marrobi** [comment]
Thanks Tom. Not sure this is a bug, but we should have a better way to clean up failed deployments, and that should be a prerequisite to doing an upgrade.
