### ISSUE TITLE
Workspace Owners and Researchers recieve browser Error and cannot see workspaces

### ISSUE THREAD

**Issue by MoSidiIC** [microsoft/AzureTRE#3489]
When a user is assigned workspace Researcher or owner along with being a member of TRE Users the recieve the error below:

(when the user is assigned TRE Admin the error disappears)

Uh oh!
This area encountered an error that we can't recover from. Please check your configuration and refresh.
Further debugging details can be found in the browser console.

The Browser console has this output:
peError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128)
ps @ react-dom.production.min.js:189
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
GenericErrorBoundary.tsx:21 UNHANDLED EXCEPTION TypeError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128) {componentStack: '\n    at WC (https://imperialtre.uksouth.cloudapp.a…pp.azure.com/static/js/main.aba16646.js:2:691445)'}
value @ GenericErrorBoundary.tsx:21
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128)
ps @ react-dom.production.min.js:189
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
GenericErrorBoundary.tsx:21 UNHANDLED EXCEPTION TypeError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128) {componentStack: '\n    at WC (https://imperialtre.uksouth.cloudapp.a…pp.azure.com/static/js/main.aba16646.js:2:691445)'}
value @ GenericErrorBoundary.tsx:21
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14

**Comment by MoSidiIC** [comment]
@LizaShak @tamirkamara @marrobi Any advice would be appreciated

**Comment by tamirkamara** [comment]
Is this on a specific screen or at the root of the TRE UI?

**Comment by marrobi** [comment]
It's on the home page/root.

**Comment by martinpeck** [comment]
A quick write up of some thoughts on this.

The error appears to be caused by the fact that the API is not returning `availableUpgrades` in some situations, for some workspaces. This causes the UI to throw an exception when it access 

There are two PRs associated with `availableUpgrades`:

- https://github.com/microsoft/AzureTRE/pull/3234 (the API changes)
- https://github.com/microsoft/AzureTRE/pull/3387 (the UI changes)

The API changes essentially make sure that `enrich_resource_with_available_upgrades` is called for every Workspace resource that the API returns, but there is a situation where we return workspaces without this enrichment.

In this `except` handler: https://github.com/microsoft/AzureTRE/blob/main/api_app/api/routes/workspaces.py#L66

The workspaces returned by line 80 (https://github.com/microsoft/AzureTRE/blob/main/api_app/api/routes/workspaces.py#L80) will be missing the `availableUpgrades` property because they have not been passed to `enrich_resource_with_available_upgrades`.

The fix is most likely adding an additional call to `enrich_resource_with_available_upgrades` between lines 79 and 80 of this `except` block, much the same way as line 63 of the `try` block does.

**Comment by martinpeck** [comment]
(the above is just a theory, and not based upon seeing this issue occur)

**Comment by MoSidiIC** [comment]
@tamirkamara 
Env background: upgraded to v 11

When a new use is granted workspace owner of Reacher, the TRE home page is inaccessible as described above

**Comment by yuvalyaron** [comment]
@martinpeck I managed to reproduce, both of your theories were right :)

**Comment by martinpeck** [comment]
Yay! That's good to know!
