### ISSUE TITLE
airlock request faield due to an unknow reason 

### ISSUE THREAD

**Issue by basitrehman531997** [microsoft/AzureTRE#3705]
Remember to label the issue with the appropriate area, and also assign it to yourself if you plan to work on the issue in the near future.

**Describe the bug**
The airlock request encountered an issue and failed after a while of being submitted. Another factor contributing to this problem is that I received an authentication error when executing a CLI command. Additionally, when I attempted to upload a file via the portal, the imported viewer virtual machine displayed an empty folder.

<img width="863" alt="airlock failed" src="https://github.com/microsoft/AzureTRE/assets/76579245/df980b1a-2531-4356-b60a-9c643175de6a">

**Comment by basitrehman531997** [comment]
also awaiting my review section is also empty

**Comment by basitrehman531997** [comment]
<img width="857" alt="awaiting my review" src="https://github.com/microsoft/AzureTRE/assets/76579245/0bc40af5-7624-4841-ac31-9f2fda11e66e">

**Comment by basitrehman531997** [comment]
<img width="944" alt="cliscreenshort" src="https://github.com/microsoft/AzureTRE/assets/76579245/dfce6b9c-f2e3-4e55-b08a-aa38ac45ee40">

**Comment by marrobi** [comment]
Hi @basitrehman531997 lets deal with the initial issue first.

Have you enabled malware scanning in the `config.yaml` - we are aware of a potential issue there?

It is could be an issue creating the storage container, or with the function that creates it.

Can you check the airlock function app logs - it is named `func-airlock-processor-....`

Also can you confirm the TRE version you are using.

Thanks.

**Comment by brehmanepicsoft** [comment]
Yes, we have implemented malware scanning in the config.yaml file 
enable_airlock_malware_scanning: true

**Comment by marrobi** [comment]
Can you try setting it to false, running `make tre-deploy`, maybe ensure the property has updated in the function app - so will be set to false.

And see if the issue still exists?

**Comment by brehmanepicsoft** [comment]
Azure TRE
UI Version:0.5.4
API Version:0.15.9
Cosmos DB:OK
Service Bus:OK
Resource Processor:Ok

is the version ?are you can tell me how to check the current version of running tre

**Comment by brehmanepicsoft** [comment]
@marrobi 
I used the command "enable-malware-scanning=false" as you instructed. But when I tried to use the app, I got this error: "We couldn't check if your function app is running, which is needed for log streaming. Please make sure your function host is running."

**Comment by marrobi** [comment]
Yes, that is fine. Are you running from `main` in this repo or the Deployment repository?

Does the airlock work? If not please send a screenshot of the function app in the portal and verify the malware scanning setting value in the function app configuration?

**Comment by brehmanepicsoft** [comment]
yes airlock not working properly give 500 error when i create request for import

**Comment by brehmanepicsoft** [comment]
this was the error when i create airlock import request 
Error submitting airlock request
Unable to process request

workspaces/e78db6e7-04e4-42cd-b538-4c909e29251c/requests
500
Error: Unable to process request at https://synhealth.eastus.cloudapp.azure.com/static/js/main.8879659a.js:2:738540 at p (https://synhealth.eastus.cloudapp.azure.com/static/js/main.8879659a.js:2:399423) at Generator.<anonymous> (https://synhealth.eastus.cloudapp.azure.com/static/js/main.8879659a.js:2:400760) at Generator.next (https://synhealth.eastus.cloudapp.azure.com/static/js/main.8879659a.js:2:399786) at i (https://synhealth.eastus.cloudapp.azure.com/static/js/main.8879659a.js:2:405415) at s (https://synhealth.eastus.cloudapp.azure.com/static/js/main.8879659a.js:2:405618)

**Comment by marrobi** [comment]
Ok, you need to check app insights or the function logs as I am not sure what is causing the issue.

Can you double check the review workspace settings are configured correctly.

**Comment by marrobi** [comment]
They look to be from a while ago? If you drill down further do you get any more info?

Anything on the front page of the function app overview - can you send a snip of that please?

**Comment by brehmanepicsoft** [comment]
oky 
<img width="953" alt="azure function" src="https://github.com/microsoft/AzureTRE/assets/142625590/97a60c0a-fb0d-488d-8b21-f92e2c68cc4a">

**Comment by marrobi** [comment]
Hmm, there is no runtime version.

@martinpeck is this not similar to what you saw, but was fixed in release v0.14.0?

@brehmanepicsoft under Deployment Center what version is the container image? Thanks.

**Comment by brehmanepicsoft** [comment]
@marrobi  how to know the version of the container image

**Comment by marrobi** [comment]
Go to Deployment Centre in the left menu of the function app.

**Comment by brehmanepicsoft** [comment]
in setting of deployment section i see tag which is 0.6.1

**Comment by brehmanepicsoft** [comment]
@marrobi  and the other question is that how to know tre version in UI or in devcontainer

**Comment by martinpeck** [comment]
That's certainly the behaviour that I'd hoped had been addressed.
Can you please review the firewall application rules that you have?
In your Azure deployment, within the resource group, you should have a Firewall Policy
In that, there are Application Rules
There should be an application rule called `functions-runtime` that looks something like this (below) and should be allow-listing the `functionscdn.azureedge.net` endpoint. Can you confirm this is present?

![image](https://github.com/microsoft/AzureTRE/assets/1524451/aa6adc66-9263-4aca-9fdd-7a5ec8aa88f7)

**Comment by marrobi** [comment]
@brehmanepicsoft  leave that off for now, I think there may be two separate issues.

Might be worth checking the firewall logs to see what traffic is being denied form the airlock processor subnet.

**Comment by brehmanepicsoft** [comment]
in activity log on tre firewall there is only one message 
Gets IP prefixes learned by Azure Firewall to not perform SNAT

**Comment by martinpeck** [comment]
OK, so that issue is different. It shouldn't be preventing the firewall (but...maybe is is? Maybe the airlock processor can't access pypi to pull packages as it starts up?)

0.14.1 fixes this. This is the only fix/change contained in 0.14.1 so can I suggest you upgrade to this and see if that fixes the airlock?

**Comment by martinpeck** [comment]
FYI this is the bug that was fixed in 0.14.1...

https://github.com/microsoft/AzureTRE/issues/3694

**Comment by martinpeck** [comment]
If you want, you can manually apply the fix that 0.14.1 includes. If you look at my screenshot of the firewall rules above you'll see that there are two pypi.org related exceptions in the very last rule. You want to allow both `pypi.org` and `*.pypi.org` and I suspect you only have the latter,.

You can manually add `pypi.org` into that rule and see if that fixes things.

0.14.1 applies this fix for you.

**Comment by martinpeck** [comment]
Red arrow shows what you want...

![image](https://github.com/microsoft/AzureTRE/assets/1524451/c4856a1f-e7e2-45f1-ad4b-50de18932750)

**Comment by brehmanepicsoft** [comment]
I attempted to address the problem, but the issue persists.

**Comment by brehmanepicsoft** [comment]
When I send a request to the airlock system, it typically produces a container for file uploads. However, the current situation is that the request no longer results in the creation of a container. Furthermore, when I check the Azure portal, I notice that there is no container defined in the request's SAS URL.

**Comment by marrobi** [comment]
Does the function have a runtime in the portal? That the issue we need to resolve. For some reason the function app isn't starting.

**Comment by brehmanepicsoft** [comment]
when i access file-system logs of function give me message 
Unable to fetch the host status of your function app. To use log streaming, please make sure your function host is running.

**Comment by brehmanepicsoft** [comment]
i also update version but in firewall you address me the issue of pypi.org is  not added automatically.
i add manually

**Comment by brehmanepicsoft** [comment]
there is no version time show only --- in fucntion

**Comment by martinpeck** [comment]
If you’ve updated the firewall perhaps stop and start the function app.

Regards, Martin

________________________________

**Comment by marrobi** [comment]
Looks like is an issue with import requests in certain circumstances:

https://github.com/microsoft/AzureTRE/issues/3767

**Comment by marrobi** [comment]
Closing as per #3767
