### ISSUE TITLE
[BUG] az login fails on codespaces

### ISSUE THREAD

**Issue by msebragge** [microsoft/AzureTRE#394]
**Describe the bug**
az login fails

**Steps to reproduce**

1. Create a new codespace from develop branch
2. Do **az login**

**Result:**
👋 Welcome to Codespaces! You are on a custom image defined in your devcontainer.json file.

🔍 To explore VS Code to its fullest, search using the Command Palette (Cmd/Ctrl + Shift + P)

📝 Edit away, then run your build command to see your code running in the browser.
vscode ➜ /workspaces/AzureTRE (develop) $ az login
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 48, in load
    with codecs_open(self.filename, 'r', encoding=self._encoding) as f:
  File "/usr/bin/../../opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vscode/.azure/azureProfile.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 38, in <module>
    az_cli = get_default_cli()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 919, in get_default_cli
    help_cls=AzCliHelp)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 80, in __init__
    ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 61, in load
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/usr/bin/../../opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/home/vscode/.azure/azureProfile.json'
vscode ➜ /workspaces/AzureTRE (develop) $ 

**Workaround:**
*sudo chmod 767 /home/vscode/.azure*

**Comment by limorl** [comment]
@msebragge I just follow the repro steps and wasn't able to reproduce. Perhaps a glitch? Is it still happening?

**Comment by Lybecker** [comment]
@msebragge have you seen this bug lately?

**Comment by marrobi** [comment]
@msebragge this should now be resolved? I'll close the issue, reopen if you think otherwise.
