### ISSUE TITLE
httpx.ConnectTimeout: _ssl.c:1118: The handshake operation timed out

### ISSUE THREAD

**Issue by radms** [microsoft/AzureTRE#3974]
Getting the following error while trying to register a new bundle after making changes to the one of the resource's porter.yaml file. Configured the New TRE Environment with latest version i.e. v0.17.0

Error

»»» 🧩  Registering /workspaces/AzureTRE-0.17.0//templates/workspace_services/azureml bundle...

╔══════════════════════════════════════╗
║          Azure TRE Makefile          ║
╚══════════════════════════════════════╝

»»» ✅ Checking pre-reqs...

Checking for Azure CLI...

Loading local environment variables...

Checking for Docker...

Checking for porter...
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: xxxxxxxxxxxxxxxxxxxx
»»»   • Tenant:       xxxxxxxxxxxxxxxxxxx

Login Succeeded
CLI already signed in
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 174, in start_tls
    raise exc
  File "/usr/local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 169, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1118: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 156, in _connect
    stream = stream.start_tls(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 174, in start_tls
    raise exc
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: _ssl.c:1118: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tre", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tre/commands/workspace_service_templates/workspace_service_template.py", line 41, in workspace_service_template_show
    response = client.call_api(
  File "/usr/local/lib/python3.8/site-packages/tre/api_client.py", line 103, in call_api
    response = client.request(method, f'{self.base_url}{url}', headers=headers, json=json_data, params=params)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:1118: The handshake operation timed out
Error checking for existing template: 
make[1]: *** [Makefile:268: bundle-register] Error 1
make[1]: Leaving directory '/workspaces/AzureTRE-0.17.0'
make: *** [Makefile:283: workspace_service_bundle] Error 2

**Comment by tim-allen-ck** [comment]
Hi @radms can you upload your porter.yaml file?
And what bundle were you trying to upload?

**Comment by radms** [comment]
@tim-allen-ck - I am trying to upload the bundle for redcap

**Comment by Danny-Cooke-CK** [comment]
@radms if these templates deployed and then subsequently you can no longer deploy to that environment then what else changed ? this is quite clearly not connecting to you environment anymore ? 

httpx.ConnectTimeout: _ssl.c:1118: The handshake operation timed out
Error checking for existing template:
make[1]: *** [Makefile:268: bundle-register] Error 1

**Comment by radms** [comment]
@Danny-Cooke-CK the environment was working before suddenly it stopped working. In ACR, can see image getting pushed successfully

**Comment by tim-allen-ck** [comment]
Hi @radms sorry, did you get this resolved? 
Have you tried pushing a change to a different template? Do you get the same errors?

**Comment by marrobi** [comment]
Closing as no activity.
