### ISSUE TITLE
[BUG] API Managed Identity issue:  Environment variables are not fully configured. 

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#446]
**Describe the bug**

Not affecting functionality but logs are full of:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 246, in _do_retryable_operation
    return await operation(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 317, in _open
    await self._handler.open_async(connection=self._connection)
  File "/usr/local/lib/python3.8/site-packages/uamqp/async_ops/client_async.py", line 246, in open_async
    await self._build_session_async()
  File "/usr/local/lib/python3.8/site-packages/uamqp/async_ops/client_async.py", line 192, in _build_session_async
    self._connection._cbs = await asyncio.shield(
  File "/usr/local/lib/python3.8/site-packages/uamqp/authentication/cbs_auth_async.py", line 279, in create_authenticator_async
    await self.update_token()
  File "/usr/local/lib/python3.8/site-packages/uamqp/authentication/cbs_auth_async.py", line 283, in update_token
    access_token = await self.get_token()
  File "/usr/local/lib/python3.8/site-packages/azure/identity/aio/_credentials/default.py", line 129, in get_token
    return await super().get_token(*scopes, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/identity/aio/_credentials/chained.py", line 80, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
	ManagedIdentityCredential: [Errno 19] No such device: '/home/api_user/.netrc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fastapi_utils/tasks.py", line 64, in loop
    await func()  # type: ignore
  File "/api/./main.py", line 59, in update_deployment_status
    await receive_message_and_update_deployment(app)
  File "/api/./service_bus/deployment_status_update.py", line 111, in receive_message_and_update_deployment
    async for message in receive_message_gen:
  File "/api/./service_bus/deployment_status_update.py", line 41, in receive_message
    async with receiver:
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 169, in __aenter__
    await self._open_with_retry()
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 370, in _open_with_retry
    return await self._do_retryable_operation(self._open)
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 250, in _do_retryable_operation
    last_exception = await self._handle_exception(exception)
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 198, in _handle_exception
    raise error
azure.servicebus.exceptions.ServiceBusError: Handler failed: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
	ManagedIdentityCredential: [Errno 19] No such device: '/home/api_user/.netrc'.
```
**Steps to reproduce**

1. Deploy API and view `traces` in Log Analytics

**Comment by sachinkundu** [comment]
I am not sure. I have seen this also. I think since the order is EnvironmentCredential first and we have some environment variables which trigger EnvironmentCredential but not all it borks. When it borks the next one ManagedIdentityCredential should pick up and it all works. 

I tried to search with that error but did not find much. Need to step into azure identity package and see why it fails.

**Comment by marrobi** [comment]
This error is no longer appearing, not sure why, maybe due to the changes in logging configuration. Will close the issue.
