### ISSUE TITLE
[BUG] Codespaces broken - starts only in recovery mode

### ISSUE THREAD

**Issue by msebragge** [microsoft/AzureTRE#687]
**Steps to reproduce**

Try to create a new codespace from develop branch

Error log:
[2021-08-21T11:37:26.134Z]  ---> Running in 5ece48717163
[2021-08-21T11:37:29.928Z] Removing intermediate container 5ece48717163
 ---> 78abf5d449f9
[2021-08-21T11:37:29.938Z] Successfully built 78abf5d449f9
[2021-08-21T11:37:29.969Z] Successfully tagged tredev:latest
[2021-08-21T11:37:30.041Z] Stop (222676 ms): Run: docker-compose --project-name azuretre_devcontainer -f /var/lib/docker/codespacemount/workspace/AzureTRE/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml build
[2021-08-21T11:37:30.042Z] Start: Run: docker-compose --project-name azuretre_devcontainer -f /var/lib/docker/codespacemount/workspace/AzureTRE/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml up -d
[2021-08-21T11:37:30.470Z] WARNING: The HOME variable is not set. Defaulting to a blank string.
WARNING: The USERPROFILE variable is not set. Defaulting to a blank string.
[2021-08-21T11:37:30.513Z] Creating network "azuretre_devcontainer_default" with the default driver
[2021-08-21T11:37:30.607Z] Creating azuretre_devcontainer_dev_1 ... 
[2021-08-21T11:37:30.616Z] 
Creating azuretre_devcontainer_dev_1 ... error
[2021-08-21T11:37:30.616Z] 
ERROR: for azuretre_devcontainer_dev_1  Cannot create container for service dev: invalid mount config for type "bind": bind source path does not exist: /.azure
[2021-08-21T11:37:30.616Z] 
ERROR: for dev  Cannot create container for service dev: invalid mount config for type "bind": bind source path does not exist: /.azure
[2021-08-21T11:37:30.617Z] ERROR: Encountered errors while bringing up the project.
Error: Command failed: docker-compose --project-name azuretre_devcontainer -f /var/lib/docker/codespacemount/workspace/AzureTRE/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml up -d
    at T5 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:279:391)
    at async xk (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:267:450)
    at async i8 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:247:9938)
    at async $G (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:293:7173)
    at async Kae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:293:26145)
    at async Yae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:293:25739)
(node:16086) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-08-21T11:37:30.677Z] Stop (635 ms): Run: docker-compose --project-name azuretre_devcontainer -f /var/lib/docker/codespacemount/workspace/AzureTRE/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml up -d
[2021-08-21T11:37:30.683Z] Stop (223321 ms): Run: docker events --format {{json .}} --filter event=start
Failed to create container.Error: Command failed: docker-compose --project-name azuretre_devcontainer -f /var/lib/docker/codespacemount/workspace/AzureTRE/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml up -dError Code: 1302Container creation failed.
2021-08-21T11:37:30: Creating recovery container.
2021-08-21T11:37:30:

**Comment by Lybecker** [comment]
This commit is the culprit https://github.com/microsoft/AzureTRE/commit/47c7ba77854e3cca34619d6afd71301812cd6da0

**Comment by christoferlof** [comment]
For 0.1 focus is WSL/Windows, Mac, Linux. Even though Codespases is Linux, let's make codespaces support as a separate effort. Might be more things we want to do then.

**Comment by christoferlof** [comment]
@Lybecker to do a bit more of investigation

**Comment by tompaana** [comment]
Tested creating a new codespace and the error is different; now about bash history:

```plaintext
[2021-09-09T13:09:12.083Z] WARNING: The HOME variable is not set. Defaulting to a blank string.
WARNING: The USERPROFILE variable is not set. Defaulting to a blank string.
[2021-09-09T13:09:12.125Z] Creating network "azuretre_devcontainer_default" with the default driver
[2021-09-09T13:09:12.228Z] Creating azuretre_devcontainer_dev_1 ... 
[2021-09-09T13:09:12.236Z] 
Creating azuretre_devcontainer_dev_1 ... error
[2021-09-09T13:09:12.236Z] 
ERROR: for azuretre_devcontainer_dev_1  Cannot create container for service dev: invalid mount config for type "bind": bind source path does not exist: /var/lib/docker/codespacemount/workspace/AzureTRE/.bash_history
[2021-09-09T13:09:12.236Z] 
ERROR: for dev  Cannot create container for service dev: invalid mount config for type "bind": bind source path does not exist: /var/lib/docker/codespacemount/workspace/AzureTRE/.bash_history
[2021-09-09T13:09:12.236Z] ERROR: Encountered errors while bringing up the project.
```
