### ISSUE TITLE
[BUG] /scripts/aad-app-reg.sh doesn't work from devcontainer, it fails on requesting endpoint: https://graph.microsoft.com/v1.0/domains

### ISSUE THREAD

**Issue by guybartal** [microsoft/AzureTRE#816]
Running ```/scripts/aad-app-reg.sh``` script I've encountered an error, it looks like it fails on requesting Microsoft graph endpoint:

```az rest -m get -u https://graph.microsoft.com/v1.0/domains -o json```

looks like I'm failing on AAD Conditional Access but only from the devcontainer, if I run it from WSL2 outside the container it works with the same az account.

**Steps to reproduce**

1. Deploy environment following this doc [https://github.com/microsoft/AzureTRE/blob/develop/docs/deployment-quickstart.md](https://github.com/microsoft/AzureTRE/blob/develop/docs/deployment-quickstart.md)
1. When you run ```/workspaces/tre> ./scripts/aad-app-reg.sh -n aztreqs -r https://aztreqs.westeurope.cloudapp.azure.com/oidc-redirect``` you will get the following error (I've run the following command on my env```./scripts/aad-app-reg.sh -n gb1-tre -r https://gb1-tre.westeurope.cloudapp.azure.com/oidc-redirect```):

```
ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
ERROR: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS53000: Device is not in required device state: compliant. Conditional Access policy requires a compliant device, and the device is not compliant. The user must enroll their device with an approved MDM provider like Intune.\r\nTrace ID: 4488a84a-9e75-46f6-8e0c-b0f2279d6a00\r\nCorrelation ID: 69bbd241-a8ac-4ba6-aa20-2ba3a9a2e3c6\r\nTimestamp: 2021-09-05 11:04:39Z","error_codes":[53000],"timestamp":"2021-09-05 11:04:39Z","trace_id":"4488a84a-9e75-46f6-8e0c-b0f2279d6a00","correlation_id":"69bbd241-a8ac-4ba6-aa20-2ba3a9a2e3c6","error_uri":"https://login.microsoftonline.com/error?code=53000","suberror":"additional_action"}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/util/custom.py", line 16, in rest_call
    r = send_raw_request(cmd.cli_ctx, method, url, headers, uri_parameters, body,
  File "/usr/lib/python3/dist-packages/azure/cli/core/util.py", line 903, in send_raw_request
    token_info, _, _ = profile.get_raw_token(resource)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_profile.py", line 675, in get_raw_token
    creds = self._creds_cache.retrieve_token_for_user(username_or_sp_id,
  File "/usr/lib/python3/dist-packages/azure/cli/core/_profile.py", line 1065, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/usr/lib/python3/dist-packages/adal/authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "/usr/lib/python3/dist-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/usr/lib/python3/dist-packages/adal/authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/usr/lib/python3/dist-packages/adal/token_request.py", line 347, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/usr/lib/python3/dist-packages/adal/token_request.py", line 127, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/usr/lib/python3/dist-packages/adal/cache_driver.py", line 198, in find
    return self._refresh_entry_if_necessary(entry,
  File "/usr/lib/python3/dist-packages/adal/cache_driver.py", line 184, in _refresh_entry_if_necessary
    return self._acquire_new_token_from_mrrt(entry)
  File "/usr/lib/python3/dist-packages/adal/cache_driver.py", line 160, in _acquire_new_token_from_mrrt
    token_response = self._refresh_function(entry, self._resource)
  File "/usr/lib/python3/dist-packages/adal/token_request.py", line 137, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/usr/lib/python3/dist-packages/adal/token_request.py", line 339, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/usr/lib/python3/dist-packages/adal/token_request.py", line 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/usr/lib/python3/dist-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS53000: Device is not in required device state: compliant. Conditional Access policy requires a compliant device, and the device is not compliant. The user must enroll their device with an approved MDM provider like Intune.\r\nTrace ID: 4488a84a-9e75-46f6-8e0c-b0f2279d6a00\r\nCorrelation ID: 69bbd241-a8ac-4ba6-aa20-2ba3a9a2e3c6\r\nTimestamp: 2021-09-05 11:04:39Z","error_codes":[53000],"timestamp":"2021-09-05 11:04:39Z","trace_id":"4488a84a-9e75-46f6-8e0c-b0f2279d6a00","correlation_id":"69bbd241-a8ac-4ba6-aa20-2ba3a9a2e3c6","error_uri":"https://login.microsoftonline.com/error?code=53000","suberror":"additional_action"}
To open an issue, please run: 'az feedback'
You are about to create App Registrations in the Azure AD Tenant .
Do you want to continue? (y/N) 
```

When running from WSL2 instead of devcontainer it works:

```
 ./scripts/aad-app-reg.sh -n gb1-tre -r https://gb1-tre.westeurope.cloudapp.azure.com/oidc-redirect
You are about to create App Registrations in the Azure AD Tenant microsoft.onmicrosoft.com.
Do you want to continue? (y/N) y
Creating a new App Registration with ID e0d750f8-312c-421e-a0c5-4803e14f6a1b
Waiting for App Registration with ID e0d750f8-312c-421e-a0c5-4803e14f6a1b to show up (1/10)...
Waiting for App Registration with ID e0d750f8-312c-421e-a0c5-4803e14f6a1b to show up (2/10)...
Waiting for App Registration with ID e0d750f8-312c-421e-a0c5-4803e14f6a1b to show up (3/10)...
Waiting for App Registration with ID e0d750f8-312c-421e-a0c5-4803e14f6a1b to show up (4/10)...
Waiting for App Registration with ID e0d750f8-312c-421e-a0c5-4803e14f6a1b to show up (5/10)...
App Registration with ID e0d750f8-312c-421e-a0c5-4803e14f6a1b found
New Service Principal created with ID e10e0c4c-1f42-49d0-9d03-715b0e77528b
WARNING: The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
gb1-tre API app password (client secret): BU.byEPT2PsI-OJbF_i9uo1NHgtzGQqi2S
Register the "gb1-treSwagger UI" application
Creating a new App Registration with ID cb474b29-d22c-48c8-9f88-6f51c29490f8
Waiting for App Registration with ID cb474b29-d22c-48c8-9f88-6f51c29490f8 to show up (1/10)...
Waiting for App Registration with ID cb474b29-d22c-48c8-9f88-6f51c29490f8 to show up (2/10)...
Waiting for App Registration with ID cb474b29-d22c-48c8-9f88-6f51c29490f8 to show up (3/10)...
Waiting for App Registration with ID cb474b29-d22c-48c8-9f88-6f51c29490f8 to show up (4/10)...
Waiting for App Registration with ID cb474b29-d22c-48c8-9f88-6f51c29490f8 to show up (5/10)...
App Registration with ID cb474b29-d22c-48c8-9f88-6f51c29490f8 found
New Service Principal created with ID 43c273da-5f15-4342-bccd-b79399b43c12
Done
```

**Comment by christoferlof** [comment]
Likely has to be run from a managed machine ? Conditional access policy?

**Comment by christoferlof** [comment]
From the error message:
> Conditional Access policy requires a compliant device

If the policy requires a compliant device and the devcontainer isn't considered to be one, nothing we can do about it atm.

**Comment by guybartal** [comment]
@christoferlof understood, we should consider fixing the docs to instruct the user who deploys the system to do it from the host machine outside devcontainer in case conditional access policy is enforced on AAD, what do you think?
