### ISSUE TITLE
[BUG] Cannot register workspace template - 500 server error

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#928]
**Describe the bug**
Trying to register a workspace template ang get a 500 error, cannot process request. Looks like a validation issue from the logs but a friendly error needs to be returned.

```
2021-09-23T20:50:39.232248077Z ERROR:root:1 validation error for ParsingModel[ResourceTemplate]
2021-09-23T20:50:39.232284278Z __root__ -> properties -> properties -> type
2021-09-23T20:50:39.232291178Z field required (type=value_error.missing)
2021-09-23T20:50:39.232296178Z Traceback (most recent call last):
2021-09-23T20:50:39.232300978Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.232306178Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.232310578Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
2021-09-23T20:50:39.232315478Z raise exc from None
2021-09-23T20:50:39.232319578Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
2021-09-23T20:50:39.232324879Z await self.app(scope, receive, sender)
2021-09-23T20:50:39.232329979Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
2021-09-23T20:50:39.232848688Z await route.handle(scope, receive, send)
2021-09-23T20:50:39.232865189Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
2021-09-23T20:50:39.232871389Z await self.app(scope, receive, send)
2021-09-23T20:50:39.232876289Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
2021-09-23T20:50:39.232882489Z response = await func(request)
2021-09-23T20:50:39.232887789Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
2021-09-23T20:50:39.232893589Z raw_response = await run_endpoint_function(
2021-09-23T20:50:39.232898789Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
2021-09-23T20:50:39.232904389Z return await dependant.call(**values)
2021-09-23T20:50:39.232909489Z File "/api/./api/routes/workspace_service_templates.py", line 37, in register_workspace_service_template
2021-09-23T20:50:39.232915089Z return template_repo.create_and_validate_template(template_input, ResourceType.WorkspaceService)
2021-09-23T20:50:39.232919990Z File "/api/./db/repositories/resource_templates.py", line 119, in create_and_validate_template
2021-09-23T20:50:39.232925490Z created_template = self.create_template(template_input, resource_type, workspace_service_template_name)
2021-09-23T20:50:39.232930590Z File "/api/./db/repositories/resource_templates.py", line 95, in create_template
2021-09-23T20:50:39.232951490Z template = parse_obj_as(ResourceTemplate, template)
2021-09-23T20:50:39.232956190Z File "pydantic/tools.py", line 35, in pydantic.tools.parse_obj_as
2021-09-23T20:50:39.232959790Z File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
2021-09-23T20:50:39.232963190Z pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[ResourceTemplate]
2021-09-23T20:50:39.232970790Z __root__ -> properties -> properties -> type
2021-09-23T20:50:39.232975691Z field required (type=value_error.missing)
2021-09-23T20:50:39.232979991Z 1 validation error for ParsingModel[ResourceTemplate]
2021-09-23T20:50:39.232984891Z __root__ -> properties -> properties -> type
2021-09-23T20:50:39.232989291Z field required (type=value_error.missing)
2021-09-23T20:50:39.232993691Z Traceback (most recent call last):
2021-09-23T20:50:39.232998191Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.233002491Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.233006291Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
2021-09-23T20:50:39.233010491Z raise exc from None
2021-09-23T20:50:39.233014891Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
2021-09-23T20:50:39.233019491Z await self.app(scope, receive, sender)
2021-09-23T20:50:39.233024091Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
2021-09-23T20:50:39.233028592Z await route.handle(scope, receive, send)
2021-09-23T20:50:39.233032992Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
2021-09-23T20:50:39.233037192Z await self.app(scope, receive, send)
2021-09-23T20:50:39.233041692Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
2021-09-23T20:50:39.233046192Z response = await func(request)
2021-09-23T20:50:39.233050692Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
2021-09-23T20:50:39.233055692Z raw_response = await run_endpoint_function(
2021-09-23T20:50:39.233060192Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
2021-09-23T20:50:39.233064892Z return await dependant.call(**values)
2021-09-23T20:50:39.233069192Z File "/api/./api/routes/workspace_service_templates.py", line 37, in register_workspace_service_template
2021-09-23T20:50:39.233073892Z return template_repo.create_and_validate_template(template_input, ResourceType.WorkspaceService)
2021-09-23T20:50:39.233078192Z File "/api/./db/repositories/resource_templates.py", line 119, in create_and_validate_template
2021-09-23T20:50:39.233088593Z created_template = self.create_template(template_input, resource_type, workspace_service_template_name)
2021-09-23T20:50:39.233093593Z File "/api/./db/repositories/resource_templates.py", line 95, in create_template
2021-09-23T20:50:39.233098393Z template = parse_obj_as(ResourceTemplate, template)
2021-09-23T20:50:39.233102393Z File "pydantic/tools.py", line 35, in pydantic.tools.parse_obj_as
2021-09-23T20:50:39.233107293Z File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
2021-09-23T20:50:39.233112493Z pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[ResourceTemplate]
2021-09-23T20:50:39.233116993Z __root__ -> properties -> properties -> type
2021-09-23T20:50:39.233121693Z field required (type=value_error.missing)
2021-09-23T20:50:39.232430881Z {'paths': ['/id'], 'kind': 'Hash', 'version': 2}
2021-09-23T20:50:39.233134693Z INFO: 169.254.129.1:51877 - "POST /api/workspace-service-templates HTTP/1.1" 500 Internal Server Error
2021-09-23T20:50:39.233869507Z ERROR: Exception in ASGI application
2021-09-23T20:50:39.233897308Z Traceback (most recent call last):
2021-09-23T20:50:39.233903208Z File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
2021-09-23T20:50:39.233908608Z result = await app(self.scope, self.receive, self.send)
2021-09-23T20:50:39.233912708Z File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
2021-09-23T20:50:39.233917308Z return await self.app(scope, receive, send)
2021-09-23T20:50:39.233921308Z File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
2021-09-23T20:50:39.233925608Z await super().__call__(scope, receive, send)
2021-09-23T20:50:39.233929008Z File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
2021-09-23T20:50:39.233932808Z await self.middleware_stack(scope, receive, send)
2021-09-23T20:50:39.233936808Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-09-23T20:50:39.233941608Z raise exc from None
2021-09-23T20:50:39.233945508Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.233949509Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.233953309Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-09-23T20:50:39.233957809Z raise exc from None
2021-09-23T20:50:39.233961909Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.233966009Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.233970309Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
2021-09-23T20:50:39.233984509Z raise exc from None
2021-09-23T20:50:39.233988609Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
2021-09-23T20:50:39.233993009Z await self.app(scope, receive, sender)
2021-09-23T20:50:39.233997109Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
2021-09-23T20:50:39.234001609Z await route.handle(scope, receive, send)
2021-09-23T20:50:39.234013410Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
2021-09-23T20:50:39.234018710Z await self.app(scope, receive, send)
2021-09-23T20:50:39.234023310Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
2021-09-23T20:50:39.234027910Z response = await func(request)
2021-09-23T20:50:39.234032310Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
2021-09-23T20:50:39.234036610Z raw_response = await run_endpoint_function(
2021-09-23T20:50:39.234042010Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
2021-09-23T20:50:39.234046810Z return await dependant.call(**values)
2021-09-23T20:50:39.234051110Z File "/api/./api/routes/workspace_service_templates.py", line 37, in register_workspace_service_template
2021-09-23T20:50:39.234056010Z return template_repo.create_and_validate_template(template_input, ResourceType.WorkspaceService)
2021-09-23T20:50:39.234060811Z File "/api/./db/repositories/resource_templates.py", line 119, in create_and_validate_template
2021-09-23T20:50:39.234065711Z created_template = self.create_template(template_input, resource_type, workspace_service_template_name)
2021-09-23T20:50:39.234070211Z File "/api/./db/repositories/resource_templates.py", line 95, in create_template
2021-09-23T20:50:39.234075511Z template = parse_obj_as(ResourceTemplate, template)
2021-09-23T20:50:39.234079811Z File "pydantic/tools.py", line 35, in pydantic.tools.parse_obj_as
2021-09-23T20:50:39.234084211Z File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
2021-09-23T20:50:39.234088511Z pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[ResourceTemplate]
2021-09-23T20:50:39.234093311Z __root__ -> properties -> properties -> type
2021-09-23T20:50:39.234098111Z field required (type=value_error.missing)
2021-09-23T20:50:39.234102611Z ERROR:uvicorn.error:Exception in ASGI application
2021-09-23T20:50:39.234107311Z Traceback (most recent call last):
2021-09-23T20:50:39.234111511Z File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
2021-09-23T20:50:39.234116012Z result = await app(self.scope, self.receive, self.send)
2021-09-23T20:50:39.234120312Z File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
2021-09-23T20:50:39.234129312Z return await self.app(scope, receive, send)
2021-09-23T20:50:39.234134512Z File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
2021-09-23T20:50:39.234139312Z await super().__call__(scope, receive, send)
2021-09-23T20:50:39.234143812Z File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
2021-09-23T20:50:39.234148612Z await self.middleware_stack(scope, receive, send)
2021-09-23T20:50:39.234152912Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-09-23T20:50:39.234157612Z raise exc from None
2021-09-23T20:50:39.234161712Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.234166313Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.234171213Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-09-23T20:50:39.234176113Z raise exc from None
2021-09-23T20:50:39.234180713Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.234185213Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.234189613Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
2021-09-23T20:50:39.234193913Z raise exc from None
2021-09-23T20:50:39.234198113Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
2021-09-23T20:50:39.234202913Z await self.app(scope, receive, sender)
2021-09-23T20:50:39.234207413Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
2021-09-23T20:50:39.234212313Z await route.handle(scope, receive, send)
2021-09-23T20:50:39.234216713Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
2021-09-23T20:50:39.234221614Z await self.app(scope, receive, send)
2021-09-23T20:50:39.234225814Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
2021-09-23T20:50:39.234230314Z response = await func(request)
2021-09-23T20:50:39.234234514Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
2021-09-23T20:50:39.234239014Z raw_response = await run_endpoint_function(
2021-09-23T20:50:39.234243714Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
2021-09-23T20:50:39.234248814Z return await dependant.call(**values)
2021-09-23T20:50:39.234253414Z File "/api/./api/routes/workspace_service_templates.py", line 37, in register_workspace_service_template
2021-09-23T20:50:39.234258214Z return template_repo.create_and_validate_template(template_input, ResourceType.WorkspaceService)
2021-09-23T20:50:39.234266114Z File "/api/./db/repositories/resource_templates.py", line 119, in create_and_validate_template
2021-09-23T20:50:39.234270614Z created_template = self.create_template(template_input, resource_type, workspace_service_template_name)
2021-09-23T20:50:39.234275115Z File "/api/./db/repositories/resource_templates.py", line 95, in create_template
2021-09-23T20:50:39.234279315Z template = parse_obj_as(ResourceTemplate, template)
2021-09-23T20:50:39.234284015Z File "pydantic/tools.py", line 35, in pydantic.tools.parse_obj_as
2021-09-23T20:50:39.234288915Z File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
2021-09-23T20:50:39.234293715Z pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[ResourceTemplate]
2021-09-23T20:50:39.234298215Z __root__ -> properties -> properties -> type
2021-09-23T20:50:39.234302915Z field required (type=value_error.missing)
2021-09-23T20:50:39.234307215Z Exception in ASGI application
2021-09-23T20:50:39.234312615Z Traceback (most recent call last):
2021-09-23T20:50:39.234316815Z File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
2021-09-23T20:50:39.234321815Z result = await app(self.scope, self.receive, self.send)
2021-09-23T20:50:39.234326315Z File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
2021-09-23T20:50:39.234331116Z return await self.app(scope, receive, send)
2021-09-23T20:50:39.234335516Z File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
2021-09-23T20:50:39.234339716Z await super().__call__(scope, receive, send)
2021-09-23T20:50:39.234343816Z File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
2021-09-23T20:50:39.234348316Z await self.middleware_stack(scope, receive, send)
2021-09-23T20:50:39.234352416Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-09-23T20:50:39.234357616Z raise exc from None
2021-09-23T20:50:39.234362216Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.234367116Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.234371816Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-09-23T20:50:39.234376216Z raise exc from None
2021-09-23T20:50:39.234380316Z File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-09-23T20:50:39.234384917Z await self.app(scope, receive, _send)
2021-09-23T20:50:39.234389117Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
2021-09-23T20:50:39.234394017Z raise exc from None
2021-09-23T20:50:39.234402717Z File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
2021-09-23T20:50:39.234407617Z await self.app(scope, receive, sender)
2021-09-23T20:50:39.234411917Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
2021-09-23T20:50:39.234416817Z await route.handle(scope, receive, send)
2021-09-23T20:50:39.234420617Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
2021-09-23T20:50:39.234424217Z await self.app(scope, receive, send)
2021-09-23T20:50:39.234428217Z File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
2021-09-23T20:50:39.234432417Z response = await func(request)
2021-09-23T20:50:39.234436417Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
2021-09-23T20:50:39.234441118Z raw_response = await run_endpoint_function(
2021-09-23T20:50:39.234445718Z File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
2021-09-23T20:50:39.234450918Z return await dependant.call(**values)
2021-09-23T20:50:39.234455218Z File "/api/./api/routes/workspace_service_templates.py", line 37, in register_workspace_service_template
2021-09-23T20:50:39.234459618Z return template_repo.create_and_validate_template(template_input, ResourceType.WorkspaceService)
2021-09-23T20:50:39.234464118Z File "/api/./db/repositories/resource_templates.py", line 119, in create_and_validate_template
2021-09-23T20:50:39.234469018Z created_template = self.create_template(template_input, resource_type, workspace_service_template_name)
2021-09-23T20:50:39.234473818Z File "/api/./db/repositories/resource_templates.py", line 95, in create_template
2021-09-23T20:50:39.234478418Z template = parse_obj_as(ResourceTemplate, template)
2021-09-23T20:50:39.234482518Z File "pydantic/tools.py", line 35, in pydantic.tools.parse_obj_as
2021-09-23T20:50:39.234487018Z File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
2021-09-23T20:50:39.234492119Z pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[ResourceTemplate]
2021-09-23T20:50:39.234496619Z __root__ -> properties -> properties -> type
2021-09-23T20:50:39.234501619Z field required (type=value_error.missing)
```

**Comment by ross-p-smith** [comment]
@marrobi - I think things have moved on so much - I wouldn't know where to start - shall we close?

**Comment by marrobi** [comment]
I was looking at this, this week. I didn't provide enough repro steps.

Although should try creating some templates with missing fields and see if get a 500 error or friendly error?
